config/routes.rb
Rails.application.routes.draw do
get 'admin' => 'admin#index'

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
	get :who_bought, on: :member
  end

root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	<script type="text/javascript">
		function startTime()
		{
			var today=new Date();
			var h=today.getHours();
			var m=today.getMinutes();
			var s=today.getSeconds();

			// add a zero in front of numbers<10
			m=checkTime(m);
			s=checkTime(s);
			if(h<12)
				document.getElementById('clock').innerHTML=h+":"+m+":"+s + " AM";
			else
				document.getElementById('clock').innerHTML=h+":"+m+":"+s + " PM";

			t=setTimeout('startTime()',500);
		}

		function checkTime(i)
		{
			if (i<10)
			{
				i="0" + i;
			}
			return i;
		}
	</script>

</head>

<%= content_tag :body, class: controller.controller_name do %>
<div id="banner">
  <%= image_tag("logo.png") %>
  <%= @page_title || "Pragmatic Bookshelf" %>
</div>

<div id="columns">
	<div id="side">
		<div id="clock"></div>
		<script type="text/javascript">startTime();</script>
		<ul>
			<li><a href="http://www....">Home</a></li>
			<li><a href="http://www..../faq">Questions</a></li>
			<li><a href="http://www..../news">News</a></li>
			<li><a href="http://www..../contact">Contact</a></li>
		</ul>
		<% if @cart %>
			<div id="cart">
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
  					<%= render @cart %>
				<% end %>
			</div>
		<% end %>
<% if session[:user_id] %>
  <br />
  <%= link_to 'Orders',   orders_path   %><br />
  <%= link_to 'Products', products_path %><br />
  <%= link_to 'Users',    users_path    %><br />
  <br />
  <%= button_to 'Logout', logout_path, :method => :delete   %>
<% end %>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
<% end %>

</html>